services:
  server:
    image: mitplan-server
    build: ./server
    volumes:
      - server-data:/app
    environment:
      - JWT_SECRET=secret
    ports:
      - "3001:3001"
  client:
    image: mitplan-client
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
volumes:
  server-data:
